### ISSUE TITLE
uninitialized constant Capistrano::Slack::Faraday

### ISSUE THREAD

**Issue by seanlinsley** [j-mcnally/capistrano-slack#29]
While upgrading our application to Rails 4 we ran into this error:

```
capistrano-slack-35112edc71d3/lib/capistrano/slack.rb:73:in `rescue in block (3 levels) in extended': uninitialized constant Capistrano::Slack::Faraday (NameError)
  from capistrano-slack-35112edc71d3/lib/capistrano/slack.rb:66:in `block (3 levels) in extended'
  from capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
  from capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
```

Other gems in our application rely on Faraday, but capistrano-slack doesn't, so it's understandable that this error would occur since Faraday hasn't actually been loaded.

**Comment by lefthand** [comment]
@ant-workaholic For me it wasn't enough to pin to 1.3.1, I had to delete 1.3.2 before I could post to slack again.

**Comment by WouterSchoofs** [comment]
what capistrano version do you have?

**Comment by lefthand** [comment]
I'm running capistrano 2.15.5

**Comment by rdsoze** [comment]
Facing the same issue with capistrano 2.15.5 and capistrano-slack 1.3.1 & 1.3.2
